#docker-compose -p periscol-back up -d
version: "3.7"

services:
  backend:
    image: periscol-back
    depends_on:
      - database
    ports: 
      - "8080:8080"
    build:
      context: .
      dockerfile: src/main/docker/back-dockerfile

  database:
    image: kaneeldias/hsqldb
    ports:
      - "9001:9001"
    environment:
      HSQLDB_USER: sa
      HSQLDB_PASSWORD: 123456789
      HSQLDB_DATABASE_ALIAS: spring

  frontend:
    image: nginx
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: src/main/docker/front-dockerfile
